# configuration for golangci-lint
run:
  go: '1.22'

linters:
  enable:
  # default
  - 'errcheck'
  - 'gosimple'
  - 'govet'
  - 'ineffassign'
  - 'staticcheck'
  - 'typecheck'
  # added
  - 'gofmt'
