# NeON build file (https://c4s4/neon)

extends: chandago/neon/golang.yml

properties:
  AUDIT_ENABLED: true

targets:

  release:
    depends: [branch, version, clean, lint, test, archive]
    doc: "Perform a release"
    steps:
    - $: [git, tag, 'v={VERSION}']
    - $: [git, push, --tags]
