# NeON build file (https://c4s4/neon)

extends: chandago/neon/golang.yml

properties:
  AUDIT_ENABLED: true

targets:

  release:
    depends: [branch, version, clean, lint, test, archive]
    doc: "Perform a release"
    steps:
    - if: 'exists("go.mod")'
      then:
      # GO project: get tag vX.Y.Z from Gitlab
      - $: [git, pull, --rebase]
      else:
      # Not a GO project: tag X.Y.Z and push to Gitlab
      - $: [git, tag, =VERSION]
      - $: [git, push, --tags]
