# NeON build file (https://c4s4/neon)

extends: chandago/neon/golang.yml
default: [lint, test, integ]

properties:
  AUDIT_ENABLED: true
  DIST_ADDRESS: 'casa@sweetohm.net:/web/app/dist/={NAME}'

targets:

  integ:
    doc: "Perform integration tests"
    depends: [clean, build]
    steps:
    - print: "Generate report with configuration"
    - $: ['={BUILD_DIR}/gobinsec', -config, test/config.yml, -verbose, test/binary]
      3x: true
      3>: '={BUILD_DIR}/report-config.yml'
    - $: [diff, test/report-config.yml, '={BUILD_DIR}/report-config.yml']
      3x: true
      3=: diff
    - if: 'diff != ""'
      then:
      - print: "diff: ={diff}"
    - print: "Generate report without configuration"
    - try:
      - $: ['={BUILD_DIR}/gobinsec', -verbose, test/binary]
        3x: true
        3>: '={BUILD_DIR}/report.yml'
    - $: [diff, test/report.yml, '={BUILD_DIR}/report.yml']
      3x: true
      3=: diff
    - if: 'diff != ""'
      then:
      - print: "diff: ={diff}"

  release:
    doc: "Perform a release"
    depends: [branch, version, lint, test, integ, archive, dist]
    steps:
    - $: [git, tag, 'v={VERSION}']
    - $: [git, push, --tags]

  dist:
    doc: "Deploy binaries on distribution server"
    steps:
    - $: 'scp ={BUILD_DIR}/={BIN_DIR}/newton-* ={DIST_ADDRESS}'
